---
title: An introduction to Python via Wordle
author: Nathan Moore
date: '2024-03-06'
slug: []
categories: []
tags: []
image: ''
showonlyimage: no
---

When Wordle first went viral I was in a group chat at work and had the idea of making a Python tutorial based on Wordle. I never did it, but this post is that introduction. I will likely do another introduction to R post as well. 

<!--more-->

When Wordle first went viral I was in a group chat at work and had the idea of making a Python tutorial based on Wordle. I never did it, but this post is that introduction. I will likely do another introduction to R post as well. 

The NY Times has [changed the source code](https://arstechnica.com/gaming/2022/02/heres-how-the-new-york-times-changed-wordle/) for Wordle ([likely in response to security concerns?](https://arstechnica.com/gaming/2022/01/beware-trolls-are-out-to-spoil-tomorrows-wordle-for-you/)) but the [Web Archive](https://web.archive.org/web/20220210031511id_/https://www.powerlanguage.co.uk/wordle/) still has the old information, including the source code and the [Javascript](/data/main.e65ce0a5.js){target="_blank"}. Thanks to [this link](https://leancrew.com/all-this/2022/02/resurrecting-the-old-wordle-for-procrastinators/) for the info. 

My idea for the tutorial is to do some analysis on the answers and the possible words. Maybe we can figure out some good starting words, find out the letter frequencies, that kind of thing. 

First I want to read in the javascript file and get the word lists into variables. Somewhat surprisingly these were always available! Sitting right there in the code. 

```{r setup, include=FALSE}
library(reticulate)
```


```{python}

with open('../../../data/main.e65ce0a5.js', 'r') as f:
    js = f.read()

```

I get an error for an unexpected character: 

```
Traceback (most recent call last):
  File "C:\Users\NATHAN~1\AppData\Local\Temp\Rtmpc1KPgv\chunk-code-7da05d317d7a.txt", line 3, in <module>
    js = f.read()
         ^^^^^^^^
  File "C:\Program Files\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 142756: character maps to <undefined>
```

When I look up position 142756 in the file, I find that it's a backspace character, and the enter character is there just afterwards. 

```{js eval=FALSE}
var s=a.detail.key;"←"===s||"Backspace"===s?e.removeLetter():"↵"===s||"Enter"===s?e.submitGuess()
```

Let's try to open with different encodings. My first guess of `utf-8` worked!

```{python}

with open('../../../data/main.e65ce0a5.js', 'r', encoding='utf-8') as f:
    js = f.read()

```

Now, from looking at the Javascript file I know that the answers are contained in a variable called `La` and the possible words in `Ta`. I can also quickly see that `La=` and `Ta=` only appear once each in the file so I can use regex to extract those strings and then turn them into proper python lists. 

I also know that "shave" is the last Wordle answer, but that is some years away. 

```{python}
# import regex
import re

# La= is the identifier for the string
# \[ want to find a literal square open bracket
# \] want to find a literal square close bracket
# (.*?) want to find the one or more of anything in a non-greedy way
# [0] findall returns a list so get the first element
answer_string = re.findall(r'La=\[(.*?)\]', js)[0]
possible_string = re.findall(r'Ta=\[(.*?)\]', js)[0]

ans_len = len(answer_string)
poss_len = len(possible_string)

```

I have long strings: `answer_string` is `r py$ans_len` characters long, and `possible_string` is `r py$poss_len` characters long. I need to make them lists. 

Note: [displaying python variables in rmarkdown](https://stackoverflow.com/questions/65344130/rmarkdown-python-inline-code-in-rmarkdown). 

```{python}

answer_list = answer_string.replace('"', '').split(',')
possible_list = possible_string.replace('"', '').split(',')

ans_len = len(answer_list)
poss_len = len(possible_list)

```

Now I have lists to work with: `answer_list` is `r py$ans_len` words long, and `possible_list` is `r py$poss_len` words long.  

